[package]
name = "app"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { path = "../../../../leptos", features = ["islands"] }
leptos_axum = { path = "../../../../integrations/axum", optional = true }
leptos_meta = { path = "../../../../meta" }
leptos_router = { path = "../../../../router" }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.40"
gloo-net = { version = "0.6.0", features = ["http"] }
reqwest = { version = "0.12.5", features = ["json"] }
axum = { version = "0.7.5", optional = true, features = ["http2"] }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.5.2", features = [
    "fs",
    "compression-gzip",
    "compression-br",
], optional = true }
tokio = { version = "1.39", features = ["full"], optional = true }
http = { version = "1.1", optional = true }
web-sys = { version = "0.3.70", features = ["AbortController", "AbortSignal"] }
wasm-bindgen = "0.2.93"
rust-embed = { version = "8.5", features = [
    "axum",
    "mime_guess",
    "tokio",
], optional = true }
mime_guess = { version = "2.0", optional = true }

[features]
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = [
    "dep:axum",
    "dep:tower",
    "dep:tower-http",
    "dep:tokio",
    "dep:http",
    "dep:rust-embed",
    "dep:mime_guess",
    "leptos/ssr",
    "leptos_axum",
    "leptos_meta/ssr",
    "leptos_router/ssr",
]

